### ISSUE TITLE
能否增加安全验证呢？放在服务器上的话很容易泄露信息

### ISSUE THREAD

**Issue by 85LA** [sub-store-org/Sub-Store-Front-End#121]
例如管理员账户登录等设置，否则只能放在本地使用。

**Comment by xream** [comment]
至于后端 推荐 https://hub.docker.com/r/xream/sub-store
使用场景:

自己使用 https://a.com/xxxxxxx 后端

分享时为 https://a.com/share/sub/a?token=yyy 此链接仅可以 GET 到订阅的结果 不暴露你的 xxxxxxx

**Comment by 85LA** [comment]
那么有这个功能的话，是不是就可以当作后端来用呢？

**Comment by 85LA** [comment]
你没理解我的意思，是指能够运营的后端，类似机场面板

**Comment by xream** [comment]
是我没理解还是你没表达清楚
现在知道了 不做

**Comment by 85LA** [comment]
呵呵，只是一个建议，是觉得你这个工具挺好的，我们交流结束了。
