### ISSUE TITLE
内置远程配置建议

### ISSUE THREAD

**Issue by macaty** [sub-store-org/Sub-Store-Front-End#86]
测试了一下，节点转换没问题，就是没有内置一些远程配置，方便开箱即用，否则用的人就少了。
参考：tindy2013/subconverter
样例地址：https://suburl.v1.mk
代码地址：https://github.com/youshandefeiyang/sub-web-modify
远程配置：https://github.com/youshandefeiyang/sub-web-modify/blob/master/src/views/Subconverter.vue

![image](https://github.com/sub-store-org/Sub-Store-Front-End/assets/16797633/e9b05e13-1402-4462-9cb3-cd2c98e6b8a6)
![image](https://github.com/sub-store-org/Sub-Store-Front-End/assets/16797633/bf99c459-a028-4f72-a72c-abd8ae4167f1)

**Comment by xream** [comment]
暂不考虑添加此功能 但是有这样的功能:
1. https://t.me/zhetengsha/1111
2. https://t.me/zhetengsha/1070
