### ISSUE TITLE
[Feature] 节点操作允许自定义操作名称

### ISSUE THREAD

**Issue by liangyi9812** [sub-store-org/Sub-Store-Front-End#90]
### 功能描述

1. 节点操作部分允许修改操作名称，支持修改、复原。
2. 修改的操作名称持久化到 gist 配置

![Capture-2024-05-12-152247](https://github.com/sub-store-org/Sub-Store-Front-End/assets/6373858/11108b33-4099-4e42-84c8-3c498ccc1540)

### 使用场景
当节点操作中含多个相同名称的操作步骤时，不易区分相同的操作。如：含有多个脚本操作时

**Comment by liangyi9812** [comment]
@xream 这个功能有必要吗

**Comment by xream** [comment]
@liangyi9812 如果有 可能更好(

**Comment by liangyi9812** [comment]
> @liangyi9812 如果有 可能更好(

好，我抽空找个时间做了，可能得先放一段时间
