### ISSUE TITLE
订阅进度样式 显示为背景时，进度接近 0% 时，显示异常

### ISSUE THREAD

**Issue by wmszhe** [sub-store-org/Sub-Store-Front-End#98]
<img width="333" alt="image" src="https://github.com/sub-store-org/Sub-Store-Front-End/assets/13552154/6c2703ae-d8b4-404c-b39c-dfc1765c6dab">

**Comment by hsingyin** [comment]
@wmszhe 这个看一佬界定一下最小的单位 或者 直接取2位小数吧

**Comment by wmszhe** [comment]
这个应该是显示问题

放大看是这样的

<img width="186" alt="image" src="https://github.com/sub-store-org/Sub-Store-Front-End/assets/13552154/bcb00b21-8826-47b3-b8b8-500e0c9c5cb3">

给 sub-item-wrapper 添加 overflow: hidden 之后，是这样的

<img width="205" alt="image" src="https://github.com/sub-store-org/Sub-Store-Front-End/assets/13552154/dee1d29f-6fa5-41b9-b83c-5ce6c48d2aed">

进度条就不会超出背景了

我不是前端，随便瞎鼓捣的，不知道这样对不对

**Comment by hsingyin** [comment]
> 这个应该是显示问题
> 
> 放大看是这样的
> 
> <img alt="image" width="186" src="https://private-user-images.githubusercontent.com/13552154/344910290-bcb00b21-8826-47b3-b8b8-500e0c9c5cb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNjYwNDgsIm5iZiI6MTcyMDA2NTc0OCwicGF0aCI6Ii8xMzU1MjE1NC8zNDQ5MTAyOTAtYmNiMDBiMjEtODgyNi00N2IzLWI4YjgtNTAwZTBjOWM1Y2IzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA0MDIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhNWEzMmI3MTlhNTVmYWI4ZjQ5ZDdlYjVmMDQ2ZDc0ZmZiZTViMWJiZGM1MjUyMWFjZmM4NTVmZTliNDNhNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I01UQy3vcKHTwDlBzK538E-eIwYXZjgtvJWa3MuqREw">
> 给 sub-item-wrapper 添加 overflow: hidden 之后，是这样的
> 
> <img alt="image" width="205" src="https://private-user-images.githubusercontent.com/13552154/344909933-dee1d29f-6fa5-41b9-b83c-5ce6c48d2aed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNjYwNDgsIm5iZiI6MTcyMDA2NTc0OCwicGF0aCI6Ii8xMzU1MjE1NC8zNDQ5MDk5MzMtZGVlMWQyOWYtNmZhNS00MWI5LWI4M2MtNWNlNmM0OGQyYWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA0MDIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyY2Q4NDY1ODVjOTQ4NmQwOGM5YWIyYWU2YTM5ZDhjNGI2YTE2ODQxODJhOWVlZGM0NDA4Njc4MjZmN2I3NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aCWcJPzS1qFDvDRJHzsa9XIzoF2rZUCMaLjqCpaHWi0">
> 进度条就不会超出背景了
> 
> 我不是前端，随便瞎鼓捣的，不知道这样对不对

@wmszhe 收到，我们会在下个版本修复这个样式问题
